-- Aula 4

-- Exercício 1: Primeira Forma Normal (1FN)

-- Tabela de Alunos
CREATE TABLE alunos (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL
);

-- Tabela de Hobbies
CREATE TABLE hobbies (
    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    descricao VARCHAR2(100) NOT NULL UNIQUE
);

-- Tabela de relacionamento (N:N)
CREATE TABLE aluno_hobby (
    aluno_id NUMBER NOT NULL,
    hobby_id NUMBER NOT NULL,
    PRIMARY KEY (aluno_id, hobby_id),
    FOREIGN KEY (aluno_id) REFERENCES alunos(id),
    FOREIGN KEY (hobby_id) REFERENCES hobbies(id)
);

-- Exercício 2: Segunda Forma Normal (2FN)

-- Pedidos
CREATE TABLE pedidos (
    id NUMBER PRIMARY KEY,
    nome_cliente VARCHAR2(100) NOT NULL
);

-- Produtos
CREATE TABLE produtos (
    id NUMBER PRIMARY KEY,
    nome_produto VARCHAR2(100) NOT NULL
);

-- Itens do Pedido (N:N)
CREATE TABLE pedido_item (
    pedido_id NUMBER NOT NULL,
    produto_id NUMBER NOT NULL,
    quantidade NUMBER NOT NULL CHECK (quantidade > 0),
    PRIMARY KEY (pedido_id, produto_id),
    FOREIGN KEY (pedido_id) REFERENCES pedidos(id),
    FOREIGN KEY (produto_id) REFERENCES produtos(id)
);


-- Exercício 3: Terceira Forma Normal (3FN)

-- Gerentes de Departamento
CREATE TABLE gerentes_departamento (
    id NUMBER PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL
);

-- Departamentos (cada departamento pode ter um gerente)
CREATE TABLE departamentos (
    id NUMBER PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    gerente_id NUMBER,
    FOREIGN KEY (gerente_id) REFERENCES gerentes_departamento(id)
);

-- Funcionários (cada funcionário pertence a um depto)
CREATE TABLE funcionarios (
    id NUMBER PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    departamento_id NUMBER NOT NULL,
    FOREIGN KEY (departamento_id) REFERENCES departamentos(id)
);


-- Exercício 4: Forma Normal de Boyce-Codd (BCNF)

-- Professores
CREATE TABLE professores (
    id NUMBER PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    sala VARCHAR2(10) NOT NULL
);

-- Disciplinas
CREATE TABLE disciplinas (
    id NUMBER PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    sala VARCHAR2(10) NOT NULL
);

-- Relacionamento Professor - Disciplina
CREATE TABLE professor_disciplina (
    professor_id NUMBER NOT NULL,
    disciplina_id NUMBER NOT NULL,
    PRIMARY KEY (professor_id, disciplina_id),
    FOREIGN KEY (professor_id) REFERENCES professores(id),
    FOREIGN KEY (disciplina_id) REFERENCES disciplinas(id)
);

-- Exercício 5: Impactos da Normalização e Quando Desnormalizar

-- Vendas Relatório (tabela desnormalizada, simplificada)
CREATE TABLE vendas_relatorio (
    id NUMBER PRIMARY KEY,
    cliente_nome VARCHAR2(100) NOT NULL,
    produto_nome VARCHAR2(100) NOT NULL,
    valor_total NUMBER(10,2) NOT NULL,
    data_venda DATE
);
