CREATE TABLE VENDAS (
    id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    produto       VARCHAR2(100) NOT NULL,
    categoria     VARCHAR2(50)  NOT NULL,
    valor         NUMBER(10,2)  NOT NULL CHECK (valor > 0),
    data_venda    DATE          DEFAULT SYSDATE,
    vendedor      VARCHAR2(100) NOT NULL
);

INSERT INTO VENDAS (produto, categoria, valor, data_venda, vendedor) 
VALUES 
    ('Notebook Dell', 'Eletrônicos', 4500.00, DATE '2025-04-01', 'Carlos'),
    ('Mouse Gamer', 'Acessórios', 150.00, DATE '2025-04-01', 'Ana'),
    ('Teclado Mecânico', 'Acessórios', 300.00, DATE '2025-04-02', 'Carlos'),
    ('Monitor 24"', 'Eletrônicos', 1200.00, DATE '2025-04-02', 'Bruna'),
    ('Fone Bluetooth', 'Acessórios', 200.00, DATE '2025-04-03', 'Ana'),
    ('Notebook HP', 'Eletrônicos', 4000.00, DATE '2025-04-03', 'Carlos'),
    ('Webcam HD', 'Acessórios', 180.00, DATE '2025-04-04', 'Bruna'),
    ('Carregador Portátil', 'Acessórios', 120.00, DATE '2025-04-04', 'Ana'),
    ('SSD 1TB', 'Componentes', 500.00, DATE '2025-04-05', 'Carlos'),
    ('Cabo HDMI', 'Acessórios', 50.00, DATE '2025-04-05', 'Bruna');

    -- 1. Criação da tabela de clientes
DROP TABLE CLIENTES PURGE;

CREATE TABLE CLIENTES (
    id_cliente    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome          VARCHAR2(100) NOT NULL,
    cidade        VARCHAR2(50),
    estado        VARCHAR2(2)
);

-- 2. Inserção de clientes
INSERT INTO CLIENTES (nome, cidade, estado) VALUES
    ('Ana', 'São Paulo', 'SP'),
    ('Bruna', 'Campinas', 'SP'),
    ('Carlos', 'Rio de Janeiro', 'RJ');

ALTER TABLE VENDAS ADD id_cliente NUMBER;
ALTER TABLE VENDAS ADD CONSTRAINT fk_cliente FOREIGN KEY (id_cliente) REFERENCES CLIENTES(id_cliente);

--1
UPDATE VENDAS
SET id_cliente = CASE vendedor
    WHEN 'Ana' THEN 1
    WHEN 'Bruna' THEN 2
    WHEN 'Carlos' THEN 3
END;
--2
SELECT
    v.produto,
    v.valor,
    c.nome AS cliente,
    c.cidade
FROM VENDAS v
INNER JOIN CLIENTES c
    ON v.id_cliente = c.id_cliente;
--3
SELECT
    c.cidade,
    COUNT(v.id) AS qtd_vendas,
    SUM(v.valor) AS total_vendas
FROM VENDAS v
INNER JOIN CLIENTES c
    ON v.id_cliente = c.id_cliente
GROUP BY c.cidade
ORDER BY total_vendas DESC;
--4
SELECT
    c.nome AS cliente,
    SUM(v.valor) AS total_gasto
FROM CLIENTES c
INNER JOIN VENDAS v
    ON c.id_cliente = v.id_cliente
GROUP BY c.nome
ORDER BY total_gasto DESC;
--5
SELECT
    c.cidade,
    v.categoria,
    COUNT(*) AS qtd_vendas,
    SUM(v.valor) AS receita
FROM VENDAS v
INNER JOIN CLIENTES c
    ON v.id_cliente = c.id_cliente
GROUP BY c.cidade, v.categoria
ORDER BY c.cidade, receita DESC;
--6
SELECT
    c.nome AS cliente,
    c.cidade,
    COUNT(v.id) AS qtd_vendas,
    SUM(v.valor) AS total_vendas,
    ROUND(AVG(v.valor), 2) AS ticket_medio
FROM CLIENTES c
INNER JOIN VENDAS v
    ON c.id_cliente = v.id_cliente
GROUP BY c.nome, c.cidade
ORDER BY total_vendas DESC;