-- 1. Criação da tabela de vendas
DROP TABLE VENDAS PURGE;

CREATE TABLE VENDAS (
    id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    produto       VARCHAR2(100) NOT NULL,
    categoria     VARCHAR2(50)  NOT NULL,
    valor         NUMBER(10,2)  NOT NULL CHECK (valor > 0),
    data_venda    DATE          DEFAULT SYSDATE,
    vendedor      VARCHAR2(100) NOT NULL
);

INSERT INTO VENDAS (produto, categoria, valor, data_venda, vendedor) 
VALUES 
    ('Notebook Dell', 'Eletrônicos', 4500.00, DATE '2025-04-01', 'Carlos'),
    ('Mouse Gamer', 'Acessórios', 150.00, DATE '2025-04-01', 'Ana'),
    ('Teclado Mecânico', 'Acessórios', 300.00, DATE '2025-04-02', 'Carlos'),
    ('Monitor 24"', 'Eletrônicos', 1200.00, DATE '2025-04-02', 'Bruna'),
    ('Fone Bluetooth', 'Acessórios', 200.00, DATE '2025-04-03', 'Ana'),
    ('Notebook HP', 'Eletrônicos', 4000.00, DATE '2025-04-03', 'Carlos'),
    ('Webcam HD', 'Acessórios', 180.00, DATE '2025-04-04', 'Bruna'),
    ('Carregador Portátil', 'Acessórios', 120.00, DATE '2025-04-04', 'Ana'),
    ('SSD 1TB', 'Componentes', 500.00, DATE '2025-04-05', 'Carlos'),
    ('Cabo HDMI', 'Acessórios', 50.00, DATE '2025-04-05', 'Bruna');


A: 

SELECT produto, data_venda, vendedor
FROM VENDAS
WHERE vendedor = 'Ana'
ORDER BY data_venda;

B:

SELECT
    categoria,
    SUM(valor) AS receita_total
FROM VENDAS
WHERE categoria = 'Eletrônicos'
GROUP BY categoria
ORDER BY receita_total DESC;

C:

SELECT produto, valor
FROM VENDAS
WHERE valor BETWEEN 200 AND 1000; 

D:

SELECT
    vendedor,
    COUNT(*) AS qtd_vendas,
    SUM(valor) AS total_vend
FROM VENDAS
GROUP BY vendedor
ORDER BY total_vend DESC;
